# Generated by Django 6.0.1 on 2026-03-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_payment_id_order_phone_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
